### ISSUE TITLE
"About Us" grammatical error

### ISSUE THREAD

**Issue by StephenGregory** [CTS-NL/old-site-2017#15]
> These meetups alternate locations between, Dooly’s and The Rocket Bakery. 

Should be:

> These meetups alternate locations between Dooly’s and The Rocket Bakery.

**Comment by MitMaro** [comment]
PR?

**Comment by NLSteveO** [comment]
Maybe add that we are adding Jumping Bean on Elizabeth Ave. to this now

**Comment by NLSteveO** [comment]
I have addressed this and also made a little update to the summary. It is now merged.
